* random walk as a markov chain
* stationary probability vector $x_{t+1} = x_t P$ (doesn't change)
    * also the eigen vector of P with an eigen val of 1
        * remember that eigenvectors are $Av = \lambda v$
* the page rank stochastic transition matrix sums to 1 for each row, since it redistributes the weights
* so say $x \in R^5$ and sums to 1, $P \in R^{5,5}$ and each row sums to 1
* eventually we get the steady state distribution $xP^n$ and $x_{t+1} = x_t P$

In [10]:
import numpy as np
x = np.array([1.0, 0.0])
x = x.reshape(1,2)
P = np.array([[0.3, 0.6], [0.5, 0.5]])

In [14]:
print x.shape, P.shape
print x.dot(P)
print x.dot(P).dot(P)
print x.dot(P).dot(P).dot(P)
print x.dot(P).dot(P).dot(P).dot(P)
print x.dot(P).dot(P).dot(P).dot(P).dot(P)

(1, 2) (2, 2)
[[ 0.3  0.6]]
[[ 0.39  0.48]]
[[ 0.357  0.474]]
[[ 0.3441  0.4512]]
[[ 0.32883  0.43206]]


* there's a proof that shows that graphs that are "well-behaved" will always converge to a stead state distribution
* properties of "well-behaved" graphs
    * irreducible (there's a path from every node to every other node) (solved by the random jump mechanism)
    * aperiodic (greatest common divisor of all cycle lengths is 1)
        * each cycle is a node to itself, so a 3 node graph that's clockwise is periodic since the GCD is 3, but one with a self loop is not, since there's a 1
* Perron-Frobenius Theorem proves it


### page rank
* have a query
* use the query to match a short list of candidate web pages
* rank the candidates via the stead state distribution

### page rank math
* $P = (1 - \alpha) P + \alpha I(1/n)$
* e.g. 85% chance of hyperlink matrix + 15% chance of identity matrix