Simple notebook for https://www.utdallas.edu/~herve/Abdi-EVD2007-pretty.pdf

In [23]:
import numpy as np

In [35]:
A = np.array([[2, 3], [2, 1]])
A

array([[2, 3],
       [2, 1]])

In [36]:
v, U = np.linalg.eig(A)

print "the eigen values are %s" % (str(v))
print "the eigen vectors are \n%s" % (str(U))

the eigen values are [ 4. -1.]
the eigen vectors are 
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


### Property 1. Au = $ \lambda $u

In [4]:
print A.dot(U[:,0])
print v[0] * U[:,0]
np.allclose(A.dot(U[:,0]), v[0] * U[:,0])

[ 3.32820118  2.21880078]
[ 3.32820118  2.21880078]


True

We can scale the eigen vector arbitrarily.

In [5]:
import random
vec = U[:,0] * int(random.random() * 50)
print vec

print A.dot(vec)
print v[0] * vec

[ 3.32820118  2.21880078]
[ 13.31280471   8.87520314]
[ 13.31280471   8.87520314]


$ (A - \lambda I)u = 0 $

In [20]:
(A - np.diag(np.array([v[0], v[0]]))).dot(U[:,0])

array([ 0.,  0.])

In [21]:
(A - np.diag(np.array([v[1], v[1]]))).dot(U[:,1])

array([ 0.,  0.])

### Property 2. $AU = U\Lambda$,  $A = U\Lambda U^{-1}$

In [26]:
Lambda = np.diag(v)
U_inverse = np.linalg.inv(U)

In [31]:
np.allclose(A.dot(U), U.dot(Lambda))

True

In [32]:
np.allclose(A, U.dot(Lambda).dot(U_inverse))

True

## From this point on, everything is focused on positive semi-definite matrices

#### Properties of **positive semi-definite** matrices:
* can be decomposed into $A = XX^T$
* $x^T A x >= 0$ for all real vector x
* positive eigenvalues
* orthogonal eigenvectors

In [38]:
A = np.array([[3, 1], [1, 3]])
v, U = np.linalg.eig(A)
Lambda = np.diag(v)

In [39]:
print "eigen values are all positive"
print Lambda

eigen values are all positive
[[ 4.  0.]
 [ 0.  2.]]


In [43]:
print "orthogonal eigenvectors"
print U
print np.allclose(np.eye(2), U.dot(U.T))

orthogonal eigenvectors
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
True


Since U are orthogonal eigenvectors, we can have the following derivation.

$ U^T U = I $

$ U^T U U^{-1} = I U^{-1} $

$ U^T = U^{-1} $



In [44]:
print np.allclose(U.T, np.linalg.inv(U))

True


This also implies

$A = U \Lambda U^{-1}$

$A = U \Lambda U^T$

In [46]:
print np.allclose(A, U.dot(Lambda).dot(U.T))

True


See the pdf for additional properties with the trace, determinant and rank