[src](https://docs.scipy.org/doc/numpy/reference/generated/numpy.tensordot.html)

In [1]:
import numpy as np

In [3]:
a = np.arange(60.).reshape(3,4,5)
print a

[[[  0.   1.   2.   3.   4.]
  [  5.   6.   7.   8.   9.]
  [ 10.  11.  12.  13.  14.]
  [ 15.  16.  17.  18.  19.]]

 [[ 20.  21.  22.  23.  24.]
  [ 25.  26.  27.  28.  29.]
  [ 30.  31.  32.  33.  34.]
  [ 35.  36.  37.  38.  39.]]

 [[ 40.  41.  42.  43.  44.]
  [ 45.  46.  47.  48.  49.]
  [ 50.  51.  52.  53.  54.]
  [ 55.  56.  57.  58.  59.]]]


In [4]:
b = np.arange(24.).reshape(4,3,2)
print b

[[[  0.   1.]
  [  2.   3.]
  [  4.   5.]]

 [[  6.   7.]
  [  8.   9.]
  [ 10.  11.]]

 [[ 12.  13.]
  [ 14.  15.]
  [ 16.  17.]]

 [[ 18.  19.]
  [ 20.  21.]
  [ 22.  23.]]]


In [6]:
c = np.tensordot(a,b, axes=([1,0],[0,1]))
print a.shape, b.shape # a [1,0] -> [4, 3] # b [0, 1] -> [4, 3]
print c.shape

(3, 4, 5) (4, 3, 2)
(5, 2)
